MSC2790 Modal Widgets
matrix-org/matrix-widget-api pull request #3
Opened 2020-10-09 08:15 UTC by t3chguy

https://github.com/matrix-org/matrix-doc/blob/travis/msc/modal-widgets/proposals/2790-modal-widgets.md

2020-10-09 15:01 UTC, turt2live requested changes
generally looks good from this side though - thanks!

2020-10-13 09:25 UTC, t3chguy commented on src/ClientWidgetApi.ts
> +    public sendWidgetConfig(data: IWidgetData): Promise<void> {
That's assuming that widget_config is only for Modal Widgets, if we choose to keep it generic then it should be any possible WidgetData as it sends `definition.data`

2020-10-13 13:51 UTC, turt2live commented on src/ClientWidgetApi.ts
> +    public sendWidgetConfig(data: IWidgetData): Promise<void> {
it's supposed to send `definition`.

2020-10-15 10:17 UTC, t3chguy commented on src/ClientWidgetApi.ts
> +    public sendWidgetConfig(data: IWidgetData): Promise<void> {
TS doesn't like it

![image](https://user-images.githubusercontent.com/2403652/96110574-f2407480-0ed7-11eb-8438-31c3573ce62d.png)

2020-10-15 10:23 UTC, t3chguy commented on src/ClientWidgetApi.ts
> +    public sendWidgetConfig(data: IWidgetData): Promise<void> {
I still think it should be IWidgetData

> The widget_config action has a data copied from the original open_modal action sent by the source widget. The client should strip any keys off the modal widget definition which are not covered by this MSC - the source widget is expected to only use the data property of the widget definition, not the root of the widget definition, to pass data through.

IWidget has creatorUserId and is missing buttons from the type. `IModalWidgetOpenRequestData` seems more appropriate

2020-10-16 18:58 UTC, turt2live approved these changes

2020-10-16 21:02 UTC, merged