Add room account data access and "since" parameter to room messages
matrix-org/matrix-widget-api pull request #84
Opened 2023-06-30 16:35 UTC by griffinli

This adds a new feature to the Widget API: the ability to receive room account data, such as "m.fully_read". It adds accompanying permissions as well, such that widgets must request permission and the user must approve the request before the widget has access to a certain eventType in room account data.

This also adds an optional parameter to readRoomEvents in which the widget can pass a "since" value (a string of an event ID). Clients can implement accompanying functionality to return only messages after the "since" event. For example, a widget can receive the value of "m.fully_read" and then pass it to readRoomEvents to receive only unread messages.

Signed-off-by: Griffin Li <griffin@beeper.com>

2023-07-03 08:52 UTC, t3chguy requested changes

2023-07-03 08:52 UTC, t3chguy commented on src/interfaces/IRoomAccountData.ts
> +export interface IRoomAccountData {
Missing copyright & license header

2023-07-03 18:02 UTC, griffinli commented
Just added the requested changes

2023-07-04 07:41 UTC, t3chguy requested changes

2023-07-04 07:41 UTC, t3chguy commented on src/interfaces/IRoomAccountData.ts
> + * Copyright 2020 The Matrix.org Foundation C.I.C.
This isn't right...

2023-07-04 07:41 UTC, t3chguy commented on src/interfaces/ReadRoomAccountDataAction.ts
> + * Copyright 2020 The Matrix.org Foundation C.I.C.
This isn't right...

2023-07-04 15:40 UTC, griffinli commented
Made changes

2023-07-05 16:45 UTC, t3chguy requested changes
CI is unhappy in places too

2023-07-05 16:45 UTC, t3chguy commented on src/interfaces/IRoomAccountData.ts
> +    room_id?: string; // eslint-disable-line camelcase
Why would room account data not have a room ID?

2023-07-05 16:45 UTC, t3chguy commented on src/interfaces/ReadEventAction.ts
> +    since?: string | undefined;
`undefined` is superfluous on an optional field

2023-07-05 16:45 UTC, t3chguy commented on src/driver/WidgetDriver.ts
> +        since: string | undefined,
```suggestion
        since?: string,
```

An optional param means the API surface is backwards compatible at the TS level

2023-07-07 17:36 UTC, griffinli commented
Thanks for the comments. Just updated

2023-07-10 08:48 UTC, t3chguy approved these changes
Looks sane other than the CI lint fail.

2023-07-12 22:18 UTC, griffinli commented
Just updated to fix the CI lint fail

2023-07-13 09:20 UTC, merged